#!/bin/bash

appname="${PWD##*/}"
mypath="$(pwd)"
RED='\033[0;31m'
GREEN='\033[0;32m'
NC='\033[0m' # No Color
config_xml='./config.xml'


if [ -e "$config_xml" ]; then
  validDirectory=false
else
  echo -e  "\n${RED}this is not a valid ionic project directory.${NC}\n"
  exit
fi


ionic cordova build android --prod  --optimizejs --minifyjs --minifycss --aot --release;


rm app-release-unsigned.apk;

cp ./platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk . ;

mv app-release-unsigned.apk $appname-release-unsigned.apk 
